model:
  name: infd
  args:
    encoder:
      name: encoder_vqf4
    z_shape:
    - 3
    - 64
    - 64
    quantizer: true
    n_embed: 8192
    decoder:
      name: decoder_vqf4
    renderer:
      name: renderer_concat_wrapper
      args:
        z_dec_channels: 128
        net:
          name: simple_renderer_net
          args:
            hidden_channels: 256
    loss_cfg:
      gan_g_loss: 0.75
    adaptive_gan_weight: true
trainer: infd_trainer
max_iter: 1000000
epoch_iter: 10000
eval_iter: 50000
save_iter: 200000
vis_iter: 100000
ckpt_select_metric:
  name: perc_loss
  type: min
optimizers:
  encoder:
    name: adam
    args:
      lr: 3.6e-05
      betas:
      - 0.5
      - 0.9
  decoder:
    name: adam
    args:
      lr: 3.6e-05
      betas:
      - 0.5
      - 0.9
  renderer:
    name: adam
    args:
      lr: 3.6e-05
      betas:
      - 0.5
      - 0.9
  disc:
    name: adam
    args:
      lr: 3.6e-05
      betas:
      - 0.5
      - 0.9
gan_start_after_iters: 0
hrft_start_after_iters: 1000000
find_unused_parameters: true
visualize:
  resolution: 256
  ds_samples: 2
  ae_center_zoom_res: 1024
datasets:
  train:
    name: wrapper_cae
    args:
      dataset:
        name: ffhq
        args:
          img_folder: ffhq_1024
          split: train
      resize_inp: 256
      resize_gt_lb: 256
      resize_gt_ub: 1024
      final_crop_gt: 256
    loader:
      batch_size: 1
      num_workers: 1
  train_hrft:
    name: wrapper_cae
    args:
      dataset:
        name: ffhq
        args:
          img_folder: ffhq_1024
          split: train
      resize_inp: 256
      resize_gt_lb: 256
      resize_gt_ub: 1024
      p_max: 0.5
      final_crop_gt: 256
    loader:
      batch_size: 1
      num_workers: 1
  val:
    name: wrapper_cae
    args:
      dataset:
        name: ffhq
        args:
          img_folder: ffhq_1024
          split: val
      resize_inp: 256
      resize_gt_lb: 256
      resize_gt_ub: 1024
      final_crop_gt: 256
    loader:
      batch_size: 1
      num_workers: 1
random_seed: null
_env:
  exp_name: ae_ffhq
  save_dir: save/ae_ffhq
  wandb: false
  resume_mode: replace
